name: debug

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}


jobs:
  #no-args:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: checkout
  #        uses: actions/checkout@v4
  #      - name: make contents of the repo unique
  #        run: |
  #          date +'%B %d, %Y %H:%M:%S %Z' > last-update.txt
  #          git config --global user.name 'jspaaks via CI'
  #          git config --global user.email 'jspaaks@users.noreply.github.com'
  #          git add last-update.txt
  #          git commit -m "bumped last update date"
  #          git push
  #      - name: Test without any input arguments / creating a draft in a new concept
  #        uses: zenodraft/action@dbg
  #        with:
  #          verbose: true


  in-concept:
      #needs: no-args
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: make contents of the repo unique
          run: |
            git config --global user.name 'jspaaks via CI'
            git config --global user.email 'jspaaks@users.noreply.github.com'
            git pull
            date +'%B %d, %Y %H:%M:%S %Z' > last-update.txt
            git add last-update.txt
            git commit -m "bumped last update date"
            git push
        - name: Test creating a draft in an existing concept
          uses: zenodraft/action@dbg
          with:
            concept: '23750'
            metadata: .github/.zenodo-in-concept.json
            verbose: true


  #with-filenames:
  #    needs: in-concept
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: checkout
  #        uses: actions/checkout@v4
  #      - name: Generate dummy files
  #        run: |
  #          echo "txt contents" > test.txt
  #          echo "pdf contents" > test.pdf
  #      - name: Test with filenames
  #        uses: zenodraft/action@dbg
  #        with:
  #          filenames: test.txt test.pdf
  #          metadata: .github/.zenodo-with-filenames.json
  #          verbose: true


  #with-compression-tar-gz:
  #    needs: with-filenames
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: checkout
  #        uses: actions/checkout@v4
  #      - name: Test with compression tar.gz instead of default zip
  #        uses: zenodraft/action@dbg
  #        with:
  #          compression: tar.gz
  #          metadata: .github/.zenodo-with-compression-tar-gz.json
  #          verbose: true


  #with-upserting:
  #    needs: with-compression-tar-gz
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: checkout
  #        uses: actions/checkout@v4
  #      - name: Test upserting the CITATION.cff with the prereserved doi
  #        uses: zenodraft/action@dbg
  #        with:
  #          upsert-doi: true
  #          upsert-location: identifiers
  #          metadata: .github/.zenodo-upserting.json
  #          filenames: CITATION.cff
  #          verbose: true
  #      - name: check CITATION.cff
  #        run: cat CITATION.cff
