name: livetests

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}


jobs:
  no-args:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: Test without any input arguments / creating a draft in a new concept
          uses: zenodraft/action@main


  in-concept:
      needs: no-args
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: Test creating a draft in an existing concept
          uses: zenodraft/action@main
          with:
            concept: '23750'
            metadata: .github/.zenodo-in-concept.json


  with-filenames:
      needs: in-concept
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: Generate dummy files
          run: |
            echo "txt contents" > test.txt
            echo "pdf contents" > test.pdf
        - name: Test with filenames
          uses: zenodraft/action@main
          with:
            filenames: test.txt test.pdf
            metadata: .github/.zenodo-with-filenames.json


  with-compression-tar-gz:
      needs: with-filenames
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: Test with compression tar.gz instead of default zip
          uses: zenodraft/action@main
          with:
            compression: tar.gz
            metadata: .github/.zenodo-with-compression-tar-gz.json


  with-upserting:
      needs: with-compression-tar-gz
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: Test upserting the CITATION.cff with the prereserved doi
          uses: zenodraft/action@main
          with:
            upsert-doi: true
            upsert-location: identifiers
            metadata: .github/.zenodo-upserting.json
            filenames: CITATION.cff
        - name: check CITATION.cff
          run: cat CITATION.cff
